# Generated by Django 6.0 on 2025-12-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='intro_pricing_used_at',
            field=models.DateTimeField(blank=True, help_text='When user first used intro pricing (one-time offer)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='intro_tier_used',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], help_text='Which tier was used with intro pricing', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='trial_tier_used',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], help_text='Which tier was used for trial (reserved for future)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='trial_used_at',
            field=models.DateTimeField(blank=True, help_text='When user first used trial (reserved for future free trials)', null=True),
        ),
    ]
