# Generated by Django 6.0 on 2026-01-06 01:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_intro_pricing_used_at_user_intro_tier_used_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneVerificationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(db_index=True, help_text='Phone number for verification (E.164 format)', max_length=20)),
                ('country_code', models.CharField(default='+237', help_text='Country code for phone number', max_length=5)),
                ('code_type', models.CharField(choices=[('phone_verification', 'Phone Verification'), ('login_verification', 'Login Verification'), ('password_reset', 'Password Reset'), ('phone_change', 'Phone Change')], db_index=True, max_length=20)),
                ('code_hash', models.CharField(help_text='Hashed verification code', max_length=255)),
                ('code_partial', models.CharField(help_text='First 4 digits for reference', max_length=4)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('expired', 'Expired'), ('revoked', 'Revoked')], db_index=True, default='pending', max_length=10)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('requested_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('requested_user_agent', models.TextField(blank=True, default='')),
                ('verified_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('verified_user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_verification_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_phone_verification_codes',
                'indexes': [models.Index(fields=['phone_number', 'code_type', 'status'], name='auth_phone__phone_n_b942e3_idx'), models.Index(fields=['user', 'code_type'], name='auth_phone__user_id_b673fe_idx'), models.Index(fields=['expires_at', 'status'], name='auth_phone__expires_84dfd5_idx'), models.Index(fields=['created_at'], name='auth_phone__created_34e5a5_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='phone_code_valid_expiration')],
            },
        ),
    ]
