# Generated by Django 6.0 on 2026-01-04 13:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspace_core', '0007_customerhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('order_created', 'New Order'), ('order_paid', 'Order Paid'), ('order_cancelled', 'Order Cancelled'), ('order_status_changed', 'Order Status Changed'), ('subscription_activated', 'Subscription Activated'), ('subscription_expired', 'Subscription Expired'), ('payment_failed', 'Payment Failed'), ('stock_low', 'Low Stock'), ('stock_out', 'Out of Stock')], db_index=True, help_text='Notification category for filtering', max_length=50)),
                ('title', models.CharField(help_text='Short notification title', max_length=255)),
                ('body', models.TextField(help_text='Notification body text', max_length=2000)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Event payload (order_id, subscription_id, etc.)')),
                ('read_at', models.DateTimeField(blank=True, db_index=True, help_text='When notification was read, null if unread', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('recipient', models.ForeignKey(help_text='User who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, help_text='Optional workspace context (for store-level notifications)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='workspace_core.workspace')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read_at', '-created_at'], name='notif_user_unread_idx'), models.Index(fields=['workspace', 'recipient', '-created_at'], name='notif_workspace_user_idx'), models.Index(fields=['recipient', 'notification_type', '-created_at'], name='notif_user_type_idx')],
            },
        ),
    ]
