# Generated by Django 6.0 on 2026-01-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order_created', 'New Order'), ('order_paid', 'Order Paid'), ('order_cancelled', 'Order Cancelled'), ('order_status_changed', 'Order Status Changed'), ('subscription_activated', 'Subscription Activated'), ('subscription_expired', 'Subscription Expired'), ('payment_failed', 'Payment Failed'), ('stock_low', 'Low Stock'), ('stock_out', 'Out of Stock'), ('subscription_renewed', 'Subscription Renewed'), ('subscription_downgraded', 'Subscription Downgraded'), ('subscription_cancelled', 'Subscription Cancelled'), ('grace_period_started', 'Grace Period Started'), ('plan_change_scheduled', 'Plan Change Scheduled'), ('plan_change_reminder', 'Plan Change Reminder'), ('renewal_reminder', 'Renewal Reminder'), ('grace_period_reminder', 'Grace Period Reminder'), ('compliance_violation', 'Compliance Violation'), ('compliance_enforced', 'Compliance Enforced')], db_index=True, help_text='Notification category for filtering', max_length=50),
        ),
    ]
