# Generated by Django 6.0 on 2025-12-09 09:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspace_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaUpload',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('3d_model', '3D Model'), ('document', 'Document')], db_index=True, help_text='Type of media (image, video, 3D model)', max_length=20)),
                ('original_filename', models.CharField(help_text='Original filename from upload', max_length=255)),
                ('file_path', models.CharField(blank=True, help_text='Storage path (works for both local and S3)', max_length=500, null=True, unique=True)),
                ('file_url', models.URLField(blank=True, help_text='Public URL to access the file', max_length=500, null=True)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(help_text='MIME type (e.g., image/jpeg, video/mp4)', max_length=100)),
                ('file_hash', models.CharField(blank=True, db_index=True, help_text='SHA256 hash of file content for deduplication', max_length=64, null=True)),
                ('width', models.IntegerField(blank=True, help_text='Image/video width in pixels', null=True)),
                ('height', models.IntegerField(blank=True, help_text='Image/video height in pixels', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('orphaned', 'Orphaned')], db_index=True, default='pending', help_text='Processing status', max_length=20)),
                ('optimized_path', models.CharField(blank=True, help_text='Path to optimized version (if applicable)', max_length=500, null=True)),
                ('thumbnail_path', models.CharField(blank=True, help_text='Path to thumbnail (if applicable)', max_length=500, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (format, duration for videos, etc.)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When the file was deleted (soft delete)', null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User who uploaded this file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_uploads', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(help_text='Workspace this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='workspace_core.workspace')),
            ],
            options={
                'verbose_name': 'Media Upload',
                'verbose_name_plural': 'Media Uploads',
                'db_table': 'medialib_uploads',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['workspace', 'uploaded_by'], name='medialib_up_workspa_9022b0_idx'), models.Index(fields=['workspace', 'media_type'], name='medialib_up_workspa_b74bff_idx'), models.Index(fields=['workspace', 'status'], name='medialib_up_workspa_7908cf_idx'), models.Index(fields=['uploaded_at'], name='medialib_up_uploade_0b6093_idx'), models.Index(fields=['workspace', 'file_hash', 'deleted_at'], name='medialib_up_workspa_1bd8cf_idx'), models.Index(fields=['workspace', 'status', 'deleted_at'], name='medialib_up_workspa_c5c30a_idx'), models.Index(fields=['deleted_at', 'uploaded_at'], name='medialib_up_deleted_d2b1b3_idx')],
            },
        ),
    ]
