# Generated by Django 6.0 on 2025-12-09 09:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspace_core', '0001_initial'),
        ('workspace_store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_id', models.CharField(help_text='Unique session identifier for guest carts', max_length=100, unique=True)),
                ('currency', models.CharField(default='XAF', help_text='Cart currency', max_length=3)),
                ('is_active', models.BooleanField(default=True, help_text='Whether cart is active')),
                ('abandoned_at', models.DateTimeField(blank=True, help_text='When cart was abandoned', null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Cart subtotal (sum of item totals)', max_digits=12)),
                ('user', models.ForeignKey(blank=True, help_text='Authenticated user (optional - for future customer accounts)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(help_text='Workspace this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='workspace_core.workspace')),
            ],
            options={
                'db_table': 'storefront_carts',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity of product in cart')),
                ('price_snapshot', models.DecimalField(decimal_places=2, help_text='Price at time of adding to cart', max_digits=12)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='workspace_storefront.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='workspace_store.product')),
                ('variant', models.ForeignKey(blank=True, help_text='Selected product variant (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='workspace_store.productvariant')),
            ],
            options={
                'db_table': 'storefront_cart_items',
            },
        ),
        migrations.CreateModel(
            name='GuestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, help_text='Unique session identifier (URL-safe token)', max_length=64, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the guest', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='Browser user agent string', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(help_text='Session expiration timestamp (default 7 days)')),
                ('cart', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_session', to='workspace_storefront.cart')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_sessions', to='workspace_core.workspace')),
            ],
            options={
                'db_table': 'storefront_guest_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['workspace', 'session_id'], name='storefront__workspa_a0f573_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['workspace', 'user', 'is_active'], name='storefront__workspa_743814_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['abandoned_at'], name='storefront__abandon_59fcae_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'product'], name='storefront__cart_id_275623_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['added_at'], name='storefront__added_a_8435ae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
        migrations.AddIndex(
            model_name='guestsession',
            index=models.Index(fields=['session_id'], name='storefront__session_c311b3_idx'),
        ),
        migrations.AddIndex(
            model_name='guestsession',
            index=models.Index(fields=['workspace', 'expires_at'], name='storefront__workspa_a60fa1_idx'),
        ),
        migrations.AddIndex(
            model_name='guestsession',
            index=models.Index(fields=['expires_at'], name='storefront__expires_60077f_idx'),
        ),
    ]
