# Generated by Django 6.0 on 2026-01-02 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace_store', '0004_order_applied_discount_order_discount_code_and_more'),
        ('workspace_storefront', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='applied_discount',
            field=models.ForeignKey(blank=True, help_text='Reference to applied discount', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='workspace_store.discount'),
        ),
        migrations.AddField(
            model_name='cart',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount amount applied to cart', max_digits=12),
        ),
        migrations.AddField(
            model_name='cart',
            name='discount_code',
            field=models.CharField(blank=True, default='', help_text='Applied discount code', max_length=50),
        ),
    ]
