# Generated by Django 6.0 on 2026-01-05 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace_store', '0008_store_profile'),
        ('workspace_storefront', '0002_cart_applied_discount_cart_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'variant')},
        ),
    ]
