# Generated by Django 6.0 on 2026-01-02 09:16

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace_core', '0006_migrate_roles_to_m2m'),
        ('workspace_store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='combine_with_other_discounts',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='is_automatic',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='minimum_order_amount',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='minimum_quantity',
        ),
        migrations.AddField(
            model_name='discount',
            name='bxgy_discount_type',
            field=models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('amount_off_each', 'Amount off each'), ('free', 'Free')], help_text='Discount type for buy_x_get_y (percentage, amount_off_each, free)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='bxgy_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discount value for buy_x_get_y', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='discount',
            name='can_combine_with_order_discounts',
            field=models.BooleanField(default=False, help_text='Can combine with order discounts'),
        ),
        migrations.AddField(
            model_name='discount',
            name='can_combine_with_product_discounts',
            field=models.BooleanField(default=False, help_text='Can combine with product discounts'),
        ),
        migrations.AddField(
            model_name='discount',
            name='customer_buys_product_ids',
            field=models.JSONField(default=list, help_text='Specific product IDs for customer buys - for buy_x_get_y'),
        ),
        migrations.AddField(
            model_name='discount',
            name='customer_buys_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Customer buys quantity - for buy_x_get_y', null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='customer_buys_type',
            field=models.CharField(blank=True, choices=[('minimum_quantity', 'Minimum quantity of items'), ('minimum_purchase_amount', 'Minimum purchase amount')], help_text='Customer buys type - for buy_x_get_y', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='customer_buys_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Customer buys minimum purchase amount - for buy_x_get_y', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='discount',
            name='customer_gets_product_ids',
            field=models.JSONField(default=list, help_text='Specific product IDs for customer gets - for buy_x_get_y'),
        ),
        migrations.AddField(
            model_name='discount',
            name='customer_gets_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Customer gets quantity - for buy_x_get_y', null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='discount_value_type',
            field=models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed Amount')], help_text='Discount value type (percentage or fixed_amount) - for amount_off_product', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='limit_one_per_customer',
            field=models.BooleanField(default=False, help_text='Whether to limit to one use per customer'),
        ),
        migrations.AddField(
            model_name='discount',
            name='limit_total_uses',
            field=models.BooleanField(default=False, help_text='Whether to limit total number of uses'),
        ),
        migrations.AddField(
            model_name='discount',
            name='max_uses_per_order',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of times discount can be used per order - for buy_x_get_y', null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='method',
            field=models.CharField(choices=[('discount_code', 'Discount Code'), ('automatic', 'Automatic Discount')], db_index=True, default='discount_code', help_text='Discount method (discount_code or automatic)', max_length=20),
        ),
        migrations.AddField(
            model_name='discount',
            name='minimum_purchase_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum purchase amount (FCFA)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='minimum_quantity_items',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum quantity of items', null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='minimum_requirement_type',
            field=models.CharField(choices=[('none', 'No minimum requirements'), ('minimum_amount', 'Minimum purchase amount'), ('minimum_quantity', 'Minimum quantity of items')], default='none', help_text='Type of minimum purchase requirement', max_length=20),
        ),
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(db_index=True, help_text='Discount code (e.g., SUMMER20, WELCOME10)', max_length=50),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(choices=[('amount_off_product', 'Amount off products'), ('buy_x_get_y', 'Buy X Get Y'), ('amount_off_order', 'Amount off order'), ('free_shipping', 'Free Shipping')], db_index=True, default='amount_off_product', help_text='Type of discount', max_length=30),
        ),
        migrations.AlterField(
            model_name='discount',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired'), ('scheduled', 'Scheduled')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='discount',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discount value - for amount_off_product', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['workspace', 'discount_type'], name='workspace_s_workspa_eb40ca_idx'),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['workspace', 'method'], name='workspace_s_workspa_d77156_idx'),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['discount_type', 'status'], name='workspace_s_discoun_623bca_idx'),
        ),
        migrations.AddConstraint(
            model_name='discount',
            constraint=models.UniqueConstraint(fields=('workspace', 'code'), name='unique_discount_code_per_workspace'),
        ),
    ]
