# Generated by Django 6.0 on 2026-01-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace_store', '0002_remove_discount_combine_with_other_discounts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='applies_to_customer_types',
            field=models.JSONField(blank=True, default=list, help_text='Customer types this discount applies to'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='applies_to_regions',
            field=models.JSONField(blank=True, default=list, help_text='Cameroon regions this discount applies to'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='category_ids',
            field=models.JSONField(blank=True, default=list, help_text='Specific category IDs this discount applies to'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='customer_buys_product_ids',
            field=models.JSONField(blank=True, default=list, help_text='Specific product IDs for customer buys - for buy_x_get_y'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='customer_gets_product_ids',
            field=models.JSONField(blank=True, default=list, help_text='Specific product IDs for customer gets - for buy_x_get_y'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='customer_segmentation',
            field=models.JSONField(blank=True, default=dict, help_text='Customer targeting rules (regions, types, tags)'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='product_ids',
            field=models.JSONField(blank=True, default=list, help_text='Specific product IDs this discount applies to'),
        ),
    ]
