# Generated by Django 6.0 on 2026-01-02 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace_store', '0003_alter_discount_applies_to_customer_types_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='applied_discount',
            field=models.ForeignKey(blank=True, help_text='Reference to applied discount (usage counted on payment)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='workspace_store.discount'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_code',
            field=models.CharField(blank=True, default='', help_text='Applied discount code (for reference)', max_length=50),
        ),
        migrations.CreateModel(
            name='OrderComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Comment content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_internal', models.BooleanField(default=True, help_text='If true, visible only to staff')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='workspace_store.order')),
            ],
            options={
                'db_table': 'store_order_comments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', '-created_at'], name='store_order_order_i_00f3ce_idx')],
            },
        ),
    ]
