# Generated by Django 6.0 on 2026-01-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace_core', '0006_migrate_roles_to_m2m'),
        ('workspace_store', '0004_order_applied_discount_order_discount_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='When order was archived', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether order is archived'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('on_hold', 'On Hold'), ('processing', 'Processing'), ('unfulfilled', 'Unfulfilled'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['workspace', 'is_archived', '-created_at'], name='store_order_workspa_747aba_idx'),
        ),
    ]
