# Generated by Django 6.0 on 2026-01-03 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace_core', '0006_migrate_roles_to_m2m'),
        ('workspace_store', '0005_order_archived_at_order_is_archived_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Order Created'), ('status_changed', 'Status Changed'), ('cancelled', 'Order Cancelled'), ('archived', 'Order Archived'), ('unarchived', 'Order Unarchived'), ('marked_as_paid', 'Marked as Paid'), ('payment_failed', 'Payment Failed'), ('refunded', 'Refunded'), ('fulfilled', 'Order Fulfilled'), ('unfulfilled', 'Order Unfulfilled'), ('partially_fulfilled', 'Partially Fulfilled'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('delivery_failed', 'Delivery Failed'), ('notes_updated', 'Notes Updated'), ('customer_notified', 'Customer Notified')], help_text='Type of action performed', max_length=50)),
                ('details', models.JSONField(default=dict, help_text='Additional context about the action (old_status, new_status, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='workspace_store.order')),
                ('performed_by', models.ForeignKey(blank=True, help_text='User who performed the action (null for system actions)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_history', to='workspace_core.workspace')),
            ],
            options={
                'verbose_name_plural': 'Order histories',
                'db_table': 'store_order_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', '-created_at'], name='store_order_order_i_bdaa32_idx'), models.Index(fields=['workspace', '-created_at'], name='store_order_workspa_bffc20_idx'), models.Index(fields=['action', '-created_at'], name='store_order_action_a4b474_idx')],
            },
        ),
    ]
