# Generated by Django 6.0 on 2026-01-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace_store', '0006_orderhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('on_hold', 'On Hold'), ('processing', 'Processing'), ('unfulfilled', 'Unfulfilled'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('returned', 'Returned')], default='pending', max_length=20),
        ),
    ]
