# Generated by Django 6.0 on 2026-01-03 10:48

import django.db.models.deletion
import uuid
import workspace.store.models.store_profile_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace_core', '0007_customerhistory'),
        ('workspace_store', '0007_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store_name', models.CharField(help_text='Display name for the store', max_length=255)),
                ('store_description', models.TextField(blank=True, default='', help_text='Store description or tagline')),
                ('logo_url', models.URLField(blank=True, default='', help_text='URL to store logo image')),
                ('store_email', models.EmailField(blank=True, default='', help_text='Primary contact email for the store', max_length=254)),
                ('support_email', models.EmailField(blank=True, default='', help_text='Customer support email (optional)', max_length=254)),
                ('phone_number', models.CharField(blank=True, default='', help_text='Store phone number (Cameroon format: +237XXXXXXXXX)', max_length=20, validators=[workspace.store.models.store_profile_model.validate_cameroon_phone])),
                ('whatsapp_number', models.CharField(blank=True, default='', help_text='WhatsApp number for order notifications (Cameroon format: +237XXXXXXXXX)', max_length=20, validators=[workspace.store.models.store_profile_model.validate_cameroon_phone])),
                ('currency', models.CharField(choices=[('XAF', 'Central African CFA franc')], default='XAF', help_text='Store currency (locked to XAF for Cameroon)', max_length=3)),
                ('timezone', models.CharField(choices=[('Africa/Douala', 'Douala (UTC+1)'), ('Africa/Lagos', 'Lagos (UTC+1)')], default='Africa/Douala', help_text='Store timezone for display purposes', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.OneToOneField(help_text='Workspace this profile belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='store_profile', to='workspace_core.workspace')),
            ],
            options={
                'verbose_name': 'Store Profile',
                'verbose_name_plural': 'Store Profiles',
                'db_table': 'store_profiles',
                'indexes': [models.Index(fields=['workspace'], name='store_profile_workspace_idx')],
            },
        ),
    ]
