# Generated by Django 6.0 on 2026-01-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace_store', '0008_store_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_region',
            field=models.CharField(db_index=True, help_text='Shipping destination region', max_length=50),
        ),
    ]
