# Generated by Django 6.0 on 2026-01-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace_store', '0009_alter_order_shipping_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_region',
            field=models.CharField(choices=[('centre', 'Centre Region'), ('littoral', 'Littoral Region'), ('west', 'West Region'), ('northwest', 'Northwest Region'), ('southwest', 'Southwest Region'), ('adamawa', 'Adamawa Region'), ('east', 'East Region'), ('far_north', 'Far North Region'), ('north', 'North Region'), ('south', 'South Region')], db_index=True, help_text='Shipping destination region', max_length=50),
        ),
    ]
