# Generated by Django 6.0 on 2026-01-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace_store', '0010_alter_order_shipping_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_address',
            field=models.JSONField(blank=True, default=dict, help_text='Billing address if different from shipping (optional for MoMo/COD)', null=True),
        ),
    ]
