# Generated by Django 6.0 on 2026-01-05 13:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0001_initial'),
        ('workspace_core', '0009_workspace_compliance_deadline_and_more'),
        ('workspace_store', '0011_alter_order_billing_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active_by_plan',
            field=models.BooleanField(db_index=True, default=True, help_text='False when product exceeds plan limit (auto-enforcement)'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['workspace', 'active_by_plan', 'is_active'], name='store_produ_workspa_0fb153_idx'),
        ),
    ]
