# Generated by Django 6.0 on 2025-12-09 09:57

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspace_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the client')),
                ('workspace', models.ForeignKey(help_text='Workspace this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='workspace_core.workspace')),
            ],
            options={
                'db_table': 'workspace_clients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Special requests or notes')),
                ('assigned_staff', models.ForeignKey(blank=True, help_text='Staff member assigned to provide the service', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='services.client')),
            ],
            options={
                'db_table': 'workspace_bookings',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('booking', models.ForeignKey(blank=True, help_text='Nullable since invoice might be general retainer', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='services.booking')),
                ('workspace', models.ForeignKey(help_text='Workspace this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='workspace_core.workspace')),
            ],
            options={
                'db_table': 'workspace_invoices',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('category', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('workspace', models.ForeignKey(help_text='Workspace this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='workspace_core.workspace')),
            ],
            options={
                'db_table': 'workspace_services',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='services.service'),
        ),
        migrations.CreateModel(
            name='ServicesProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_name', models.CharField(default='My Services', max_length=200)),
                ('business_description', models.TextField(blank=True)),
                ('booking_advance_days', models.PositiveIntegerField(default=30, help_text='How many days in advance clients can book')),
                ('booking_notice_hours', models.PositiveIntegerField(default=24, help_text='Minimum notice required for booking (in hours)')),
                ('business_hours_start', models.TimeField(default='09:00:00')),
                ('business_hours_end', models.TimeField(default='17:00:00')),
                ('working_days', models.JSONField(default=list, help_text='List of working days (0=Monday, 6=Sunday)')),
                ('require_payment_upfront', models.BooleanField(default=False)),
                ('accept_online_payments', models.BooleanField(default=True)),
                ('send_booking_confirmations', models.BooleanField(default=True)),
                ('send_booking_reminders', models.BooleanField(default=True)),
                ('reminder_hours_before', models.PositiveIntegerField(default=24)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_extension', to='workspace_core.workspace')),
            ],
            options={
                'verbose_name': 'Services Profile',
                'verbose_name_plural': 'Services Profiles',
                'db_table': 'workspace_services_profiles',
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['workspace', 'email'], name='workspace_c_workspa_89913b_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['name'], name='workspace_c_name_d06bc6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('workspace', 'email')},
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['workspace', 'status'], name='workspace_i_workspa_e46d69_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['issued_at'], name='workspace_i_issued__61504a_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['booking'], name='workspace_i_booking_367beb_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='workspace_i_invoice_a1509b_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['workspace', 'is_active'], name='workspace_s_workspa_4e5eb0_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['price'], name='workspace_s_price_3e6023_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['service', 'status'], name='workspace_b_service_284c8c_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['scheduled_at'], name='workspace_b_schedul_ee7092_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['client'], name='workspace_b_client__da5e6d_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['assigned_staff'], name='workspace_b_assigne_fe93d1_idx'),
        ),
    ]
