# Generated by Django 6.0 on 2025-12-09 09:57

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspace_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('customer_registered', 'Customer Registered'), ('order_created', 'New Order'), ('payment_successful', 'Payment Successful'), ('inventory_low', 'Low Stock'), ('inventory_out', 'Out of Stock')], max_length=50)),
                ('target_object_id', models.CharField(help_text='ID of the related object', max_length=100)),
                ('target_content_type', models.CharField(help_text='Model name of the related object', max_length=100)),
                ('title', models.CharField(help_text='Display title for the activity', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the event')),
                ('metadata', models.JSONField(default=dict, help_text='Flexible event data storage')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User who triggered the event', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to='workspace_core.workspace')),
            ],
            options={
                'db_table': 'analytics_activity_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', '-created_at'], name='analytics_a_workspa_cb039a_idx'), models.Index(fields=['workspace', 'event_type', '-created_at'], name='analytics_a_workspa_43e0d2_idx'), models.Index(fields=['workspace', 'priority', '-created_at'], name='analytics_a_workspa_030fd9_idx')],
            },
        ),
        migrations.CreateModel(
            name='StoreOverviewMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_orders', models.IntegerField(default=0)),
                ('total_customers', models.IntegerField(default=0)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_products', models.IntegerField(default=0)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('revenue_growth', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('order_growth', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_overview_metrics', to='workspace_core.workspace')),
            ],
            options={
                'db_table': 'analytics_store_overview_metrics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['workspace', '-date'], name='analytics_s_workspa_856763_idx'), models.Index(fields=['date'], name='analytics_s_date_0b95ac_idx')],
                'unique_together': {('workspace', 'date')},
            },
        ),
    ]
