# Generated by Django 6.0 on 2026-01-04 06:39

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace_analytics', '0001_initial'),
        ('workspace_core', '0007_customerhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(db_index=True, help_text='Customer session identifier (cookie-based, resets after order or 24h)')),
                ('event_type', models.CharField(choices=[('order_completed', 'Order Completed'), ('order_failed', 'Order Failed'), ('store_page_view', 'Store Page View'), ('add_to_cart', 'Add to Cart'), ('product_view', 'Product View'), ('checkout_started', 'Checkout Started'), ('customer_created', 'Customer Created'), ('cart_abandoned', 'Cart Abandoned'), ('customer_returned', 'Customer Returned'), ('coupon_applied', 'Coupon Applied'), ('order_refunded', 'Order Refunded'), ('delivery_completed', 'Delivery Completed')], db_index=True, help_text='Event type from taxonomy', max_length=30)),
                ('order_value', models.DecimalField(blank=True, decimal_places=2, help_text='Order total amount', max_digits=12, null=True)),
                ('items_count', models.IntegerField(blank=True, help_text='Number of items in order', null=True)),
                ('currency', models.CharField(default='XAF', help_text='Currency code (XAF for Cameroon)', max_length=3)),
                ('payment_method', models.CharField(blank=True, choices=[('mobile_money', 'Mobile Money'), ('cash_on_delivery', 'Cash on Delivery'), ('card', 'Credit/Debit Card'), ('whatsapp', 'WhatsApp Order'), ('bank_transfer', 'Bank Transfer')], help_text='Payment method used', max_length=20, null=True)),
                ('order_id', models.UUIDField(blank=True, db_index=True, help_text='Reference to Order if applicable', null=True)),
                ('product_id', models.UUIDField(blank=True, db_index=True, help_text='Reference to Product if applicable', null=True)),
                ('customer_id', models.UUIDField(blank=True, db_index=True, help_text='Reference to Customer if applicable', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional event context (kept minimal)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When event occurred')),
            ],
            options={
                'db_table': 'analytics_store_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreMetricsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Date this snapshot represents')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of order_value from order_completed events', max_digits=14)),
                ('total_orders', models.IntegerField(default=0, help_text='Count of order_completed events')),
                ('failed_orders', models.IntegerField(default=0, help_text='Count of order_failed events')),
                ('payment_mobile_money', models.IntegerField(default=0, help_text='Orders paid via Mobile Money')),
                ('payment_cash_on_delivery', models.IntegerField(default=0, help_text='Orders paid via Cash on Delivery')),
                ('payment_card', models.IntegerField(default=0, help_text='Orders paid via Card')),
                ('payment_whatsapp', models.IntegerField(default=0, help_text='Orders via WhatsApp')),
                ('payment_bank_transfer', models.IntegerField(default=0, help_text='Orders paid via Bank Transfer')),
                ('page_views', models.IntegerField(default=0, help_text='Count of store_page_view events')),
                ('unique_sessions', models.IntegerField(default=0, help_text='Count of unique session_ids for the day')),
                ('product_views', models.IntegerField(default=0, help_text='Count of product_view events')),
                ('add_to_cart_count', models.IntegerField(default=0, help_text='Count of add_to_cart events')),
                ('checkout_started_count', models.IntegerField(default=0, help_text='Count of checkout_started events')),
                ('cart_abandoned_count', models.IntegerField(default=0, help_text='Count of cart_abandoned events')),
                ('new_customers', models.IntegerField(default=0, help_text='Count of customer_created events')),
                ('returning_customers', models.IntegerField(default=0, help_text='Count of customer_returned events')),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='(total_orders / page_views) * 100', max_digits=5)),
                ('cart_abandonment_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='(cart_abandoned / checkout_started) * 100', max_digits=5)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='total_revenue / total_orders', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'analytics_store_metrics_snapshots',
                'ordering': ['-date'],
            },
        ),
        migrations.RemoveIndex(
            model_name='activityevent',
            name='analytics_a_workspa_cb039a_idx',
        ),
        migrations.RemoveIndex(
            model_name='activityevent',
            name='analytics_a_workspa_43e0d2_idx',
        ),
        migrations.RemoveIndex(
            model_name='activityevent',
            name='analytics_a_workspa_030fd9_idx',
        ),
        migrations.AlterUniqueTogether(
            name='storeoverviewmetrics',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='storeoverviewmetrics',
            name='analytics_s_workspa_856763_idx',
        ),
        migrations.RemoveIndex(
            model_name='storeoverviewmetrics',
            name='analytics_s_date_0b95ac_idx',
        ),
        migrations.AddField(
            model_name='storeevent',
            name='workspace',
            field=models.ForeignKey(help_text='Store/workspace this event belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='store_events', to='workspace_core.workspace'),
        ),
        migrations.AddField(
            model_name='storemetricssnapshot',
            name='workspace',
            field=models.ForeignKey(help_text='Store/workspace this snapshot belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='metrics_snapshots', to='workspace_core.workspace'),
        ),
        migrations.RemoveField(
            model_name='activityevent',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='activityevent',
            name='workspace',
        ),
        migrations.RemoveField(
            model_name='storeoverviewmetrics',
            name='workspace',
        ),
        migrations.AddIndex(
            model_name='storeevent',
            index=models.Index(fields=['workspace', '-created_at'], name='analytics_s_workspa_8cf1e4_idx'),
        ),
        migrations.AddIndex(
            model_name='storeevent',
            index=models.Index(fields=['workspace', 'event_type', '-created_at'], name='analytics_s_workspa_5d24dd_idx'),
        ),
        migrations.AddIndex(
            model_name='storeevent',
            index=models.Index(fields=['workspace', 'session_id'], name='analytics_s_workspa_10b2d6_idx'),
        ),
        migrations.AddIndex(
            model_name='storeevent',
            index=models.Index(fields=['workspace', 'event_type', 'payment_method'], name='analytics_s_workspa_79ba83_idx'),
        ),
        migrations.AddIndex(
            model_name='storeevent',
            index=models.Index(fields=['workspace', 'created_at'], name='analytics_s_workspa_5e7cab_idx'),
        ),
        migrations.AddIndex(
            model_name='storemetricssnapshot',
            index=models.Index(fields=['workspace', '-date'], name='analytics_s_workspa_bf6a41_idx'),
        ),
        migrations.AddIndex(
            model_name='storemetricssnapshot',
            index=models.Index(fields=['date'], name='analytics_s_date_cebcbf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storemetricssnapshot',
            unique_together={('workspace', 'date')},
        ),
        migrations.DeleteModel(
            name='ActivityEvent',
        ),
        migrations.DeleteModel(
            name='StoreOverviewMetrics',
        ),
    ]
