# Generated by Django 6.0 on 2025-12-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace_hosting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostingenvironment',
            name='capabilities',
            field=models.JSONField(blank=True, default=dict, help_text='Hosting entitlements: storage_gb, custom_domain, deployment_allowed'),
        ),
    ]
