# Generated by Django 6.0 on 2025-12-13 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace_hosting', '0002_hostingenvironment_capabilities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostingenvironment',
            name='bandwidth_limit_gb',
        ),
        migrations.RemoveField(
            model_name='hostingenvironment',
            name='custom_domains_limit',
        ),
        migrations.RemoveField(
            model_name='hostingenvironment',
            name='sites_limit',
        ),
        migrations.RemoveField(
            model_name='hostingenvironment',
            name='storage_limit_gb',
        ),
    ]
