# Generated by Django 6.0 on 2025-12-17 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace_hosting', '0003_remove_hostingenvironment_bandwidth_limit_gb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployedsite',
            name='hosting_environment',
            field=models.ForeignKey(help_text='Resource quota tracker for this deployment', on_delete=django.db.models.deletion.CASCADE, related_name='deployed_sites', to='workspace_hosting.hostingenvironment'),
        ),
    ]
