# Generated by Django 6.0 on 2025-12-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace_hosting', '0004_alter_deployedsite_hosting_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployedsite',
            name='password_hash',
            field=models.CharField(blank=True, help_text="Hashed password for storefront access (Django's make_password)", max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='deployedsite',
            name='password_protection_enabled',
            field=models.BooleanField(default=False, help_text='Enable password protection for storefront (prevents public access)'),
        ),
        migrations.AddField(
            model_name='deployedsite',
            name='seo_description',
            field=models.TextField(blank=True, default='', help_text='Meta description for search results (max 160 chars)', max_length=160),
        ),
        migrations.AddField(
            model_name='deployedsite',
            name='seo_image_url',
            field=models.URLField(blank=True, default='', help_text='Open Graph image for social sharing (Facebook, Twitter, WhatsApp)'),
        ),
        migrations.AddField(
            model_name='deployedsite',
            name='seo_keywords',
            field=models.CharField(blank=True, default='', help_text='Comma-separated keywords (optional, less important for modern SEO)', max_length=255),
        ),
        migrations.AddField(
            model_name='deployedsite',
            name='seo_title',
            field=models.CharField(blank=True, default='', help_text='SEO title for search engines (max 60 chars for Google)', max_length=60),
        ),
    ]
