# Generated by Django 6.0 on 2025-12-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace_hosting', '0005_deployedsite_password_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployedsite',
            name='password_plaintext',
            field=models.CharField(blank=True, default='', help_text='Plaintext password for storefront (Shopify pattern: show to merchant)', max_length=128),
        ),
    ]
