# Generated by Django 6.0 on 2026-01-03 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_merchantpaymentmethod_checkout_url_and_more'),
        ('workspace_hosting', '0006_deployedsite_password_plaintext'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainpurchase',
            name='payment_intent',
            field=models.OneToOneField(blank=True, help_text='Linked payment intent for this purchase', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain_purchase', to='payments.paymentintent'),
        ),
    ]
