# Generated by Django 6.0 on 2026-01-03 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_merchantpaymentmethod_checkout_url_and_more'),
        ('workspace_hosting', '0007_domainpurchase_payment_intent'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainrenewal',
            name='payment_intent',
            field=models.OneToOneField(blank=True, help_text='Linked payment intent for this renewal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain_renewal', to='payments.paymentintent'),
        ),
    ]
