# Generated by Django 6.0 on 2026-01-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace_hosting', '0008_domainrenewal_payment_intent'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployedsite',
            name='password_description',
            field=models.CharField(blank=True, default='', help_text="Message shown to visitors on password page (e.g., 'Store coming soon!')", max_length=255),
        ),
    ]
