# Generated by Django 6.0 on 2025-12-09 09:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspace_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(choices=[('product.created', 'Product Created'), ('product.updated', 'Product Updated'), ('product.deleted', 'Product Deleted'), ('order.created', 'Order Created'), ('order.updated', 'Order Updated'), ('post.created', 'Post Created'), ('post.updated', 'Post Updated'), ('post.published', 'Post Published'), ('post.deleted', 'Post Deleted'), ('service.created', 'Service Created'), ('service.updated', 'Service Updated'), ('booking.created', 'Booking Created'), ('booking.updated', 'Booking Updated'), ('workspace.settings_updated', 'Workspace Settings Updated'), ('workspace.branding_updated', 'Workspace Branding Updated')], max_length=50)),
                ('entity_type', models.CharField(help_text='Model name (Product, Post, etc.)', max_length=50)),
                ('entity_id', models.CharField(help_text='ID of the changed entity', max_length=100)),
                ('event_data', models.JSONField(help_text='Event payload data')),
                ('changed_fields', models.JSONField(default=list, help_text='List of changed field names')),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('sites_to_sync', models.JSONField(default=list, help_text='List of site IDs to sync')),
                ('sites_synced', models.JSONField(default=list, help_text='List of successfully synced site IDs')),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=8)),
                ('triggered_by_user_id', models.CharField(blank=True, help_text='User who triggered the change', max_length=100)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('workspace', models.ForeignKey(help_text='Workspace this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='workspace_core.workspace')),
            ],
            options={
                'db_table': 'workspace_sync_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Metrics date')),
                ('events_generated', models.PositiveIntegerField(default=0)),
                ('events_processed', models.PositiveIntegerField(default=0)),
                ('events_failed', models.PositiveIntegerField(default=0)),
                ('webhooks_sent', models.PositiveIntegerField(default=0)),
                ('webhooks_delivered', models.PositiveIntegerField(default=0)),
                ('webhooks_failed', models.PositiveIntegerField(default=0)),
                ('avg_delivery_time_ms', models.PositiveIntegerField(default=0)),
                ('max_delivery_time_ms', models.PositiveIntegerField(default=0)),
                ('polls_completed', models.PositiveIntegerField(default=0)),
                ('polls_with_changes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_metrics', to='workspace_core.workspace')),
            ],
            options={
                'db_table': 'workspace_sync_metrics',
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('target_site_id', models.CharField(help_text='Target deployed site ID', max_length=100)),
                ('target_url', models.URLField(help_text='Webhook endpoint URL')),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('timeout', 'Timeout'), ('retry_scheduled', 'Retry Scheduled')], default='pending', max_length=20)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('scheduled_at', models.DateTimeField(help_text='When delivery is scheduled')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('response_received_at', models.DateTimeField(blank=True, null=True)),
                ('http_status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('response_headers', models.JSONField(blank=True, default=dict)),
                ('response_body', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('request_duration_ms', models.PositiveIntegerField(blank=True, help_text='Request duration in milliseconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_deliveries', to='workspace_sync.syncevent')),
            ],
            options={
                'db_table': 'workspace_webhook_deliveries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PollingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_poll_at', models.DateTimeField(help_text='Last successful poll time')),
                ('last_change_detected_at', models.DateTimeField(blank=True, help_text='Last time changes were detected', null=True)),
                ('next_poll_at', models.DateTimeField(help_text='Next scheduled poll time')),
                ('is_polling_active', models.BooleanField(default=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('max_failures', models.PositiveIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='polling_state', to='workspace_core.workspace')),
            ],
            options={
                'db_table': 'workspace_polling_states',
                'indexes': [models.Index(fields=['next_poll_at', 'is_polling_active'], name='workspace_p_next_po_7efbb0_idx'), models.Index(fields=['workspace'], name='workspace_p_workspa_839eb0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='syncevent',
            index=models.Index(fields=['workspace', 'sync_status', '-created_at'], name='workspace_s_workspa_472bb9_idx'),
        ),
        migrations.AddIndex(
            model_name='syncevent',
            index=models.Index(fields=['event_type', 'sync_status'], name='workspace_s_event_t_fdc42a_idx'),
        ),
        migrations.AddIndex(
            model_name='syncevent',
            index=models.Index(fields=['entity_type', 'entity_id'], name='workspace_s_entity__81837f_idx'),
        ),
        migrations.AddIndex(
            model_name='syncevent',
            index=models.Index(fields=['event_id'], name='workspace_s_event_i_2d0303_idx'),
        ),
        migrations.AddIndex(
            model_name='syncmetrics',
            index=models.Index(fields=['workspace', 'date'], name='workspace_s_workspa_391477_idx'),
        ),
        migrations.AddIndex(
            model_name='syncmetrics',
            index=models.Index(fields=['date'], name='workspace_s_date_751a37_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='syncmetrics',
            unique_together={('workspace', 'date')},
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['sync_event', 'attempt_number'], name='workspace_w_sync_ev_29d0a7_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['delivery_status', 'scheduled_at'], name='workspace_w_deliver_603bb0_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['target_site_id', '-created_at'], name='workspace_w_target__2f9270_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['delivery_id'], name='workspace_w_deliver_c2e23f_idx'),
        ),
    ]
