# Generated by Django 6.0 on 2025-12-10 02:34

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('subscription', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertrialeligibility',
            name='user',
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='charge_type',
            field=models.CharField(choices=[('subscription', 'Subscription'), ('subscription_renewal', 'Subscription Renewal'), ('subscription_upgrade', 'Subscription Upgrade'), ('domain', 'Domain'), ('domain_renewal', 'Domain Renewal'), ('theme', 'Theme'), ('checkout', 'Checkout'), ('addon', 'Add-on'), ('other', 'Other')], default='subscription', help_text='Type of charge (derived from PaymentIntent.purpose)', max_length=30),
        ),
        migrations.AddField(
            model_name='subscriptionhistory',
            name='bill_number',
            field=models.CharField(default=django.utils.timezone.now, editable=False, help_text='Human-readable bill number (e.g., #452157574)', max_length=120, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionhistory',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('pending', 'Pending')], default='unpaid', help_text='Payment status of this bill', max_length=120),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['charge_type'], name='subscriptio_charge__f83b58_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['user', 'charge_type'], name='subscriptio_user_id_cfb870_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionhistory',
            index=models.Index(fields=['bill_number'], name='subscriptio_bill_nu_1d4a50_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionhistory',
            index=models.Index(fields=['status'], name='subscriptio_status_d8cd46_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionhistory',
            index=models.Index(fields=['subscription', 'status'], name='subscriptio_subscri_5a6528_idx'),
        ),
        migrations.DeleteModel(
            name='UserTrialEligibility',
        ),
    ]
