# Generated by Django 6.0 on 2025-12-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_remove_usertrialeligibility_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', help_text='Billing cycle duration', max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='currency',
            field=models.CharField(default='XAF', help_text='Currency code (ISO 4217)', max_length=10),
        ),
    ]
