# Generated by Django 6.0 on 2025-12-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_subscription_billing_cycle_subscription_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['regular_price_monthly'], 'verbose_name': 'Subscription Plan', 'verbose_name_plural': 'Subscription Plans'},
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='price_fcfa',
        ),
        migrations.AddField(
            model_name='subscription',
            name='billing_phase',
            field=models.CharField(choices=[('intro', 'Intro Pricing'), ('regular', 'Regular Pricing')], default='regular', help_text='Current billing phase - intro pricing or regular pricing', max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='current_cycle_ends_at',
            field=models.DateTimeField(blank=True, help_text='When current billing cycle ends', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='current_cycle_started_at',
            field=models.DateTimeField(blank=True, help_text='When current billing cycle started', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='intro_cycles_remaining',
            field=models.IntegerField(default=0, help_text='Number of intro cycles remaining (typically 1 for 28-day intro)'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='intro_duration_days',
            field=models.IntegerField(default=28, help_text='Intro period duration in days (default: 28)'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='intro_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Intro price for 28-day first cycle (first-time users only)', max_digits=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='regular_price_monthly',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Regular monthly price (30 days)', max_digits=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='regular_price_yearly',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Regular yearly price (365 days)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', help_text='Billing cycle duration (monthly = 30 days, yearly = 365 days)', max_length=20),
        ),
    ]
