# Generated by Django 6.0 on 2026-01-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_alter_subscriptionplan_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('beginning', 'Beginning'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], max_length=20, unique=True),
        ),
    ]
