# Generated by Django 6.0 on 2026-01-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_alter_subscriptionplan_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('change_pending', 'Change Pending'), ('active', 'Active'), ('expired', 'Expired'), ('grace_period', 'Grace Period'), ('restricted', 'Restricted'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
    ]
