# Generated by Django 6.0 on 2025-12-09 09:57

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('editor', 'Editor'), ('viewer', 'Viewer')], help_text='Role name', max_length=50)),
                ('permissions', models.JSONField(default=list, help_text='List of permissions for this role')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'workspace_roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Workspace display name', max_length=255)),
                ('type', models.CharField(choices=[('store', 'Store'), ('blog', 'Blog'), ('services', 'Services')], help_text='Workspace type determines available features', max_length=20)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional workspace description')),
                ('status', models.CharField(choices=[('provisioning', 'Provisioning'), ('active', 'Active'), ('suspended', 'Suspended'), ('pending', 'Pending Approval')], default='provisioning', max_length=20)),
                ('provisioning_complete', models.BooleanField(default=False, help_text='True when all background provisioning tasks complete')),
                ('capabilities', models.JSONField(blank=True, default=dict, help_text='Merged capability map from CapabilityEngine - runtime source of truth for features')),
                ('is_demo', models.BooleanField(db_index=True, default=False, help_text='Whether this workspace is a demo workspace for theme preview')),
                ('is_admin_managed', models.BooleanField(db_index=True, default=False, help_text='Whether this workspace is managed by admins (bypasses subscription limits)')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text="When workspace was soft-deleted (status='suspended')", null=True)),
                ('deletion_scheduled_for', models.DateTimeField(blank=True, db_index=True, help_text='When permanent deletion/deprovisioning will occur (deleted_at + 5 days)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workspaces',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProvisioningRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0, help_text='Number of times provisioning has been retried')),
                ('max_retries', models.IntegerField(default=5, help_text='Maximum number of automatic retries allowed')),
                ('last_retry_at', models.DateTimeField(blank=True, help_text='Timestamp of last retry attempt', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provisioning', to='workspace_core.workspace')),
            ],
            options={
                'db_table': 'workspace_provisioning_records',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, help_text='Whether membership is active')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='workspace_core.role')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='workspace_core.workspace')),
            ],
            options={
                'db_table': 'workspace_memberships',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='DeProvisioningRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('scheduled_for', models.DateTimeField(help_text='When deprovisioning should execute (after grace period)')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('cleanup_metadata', models.JSONField(blank=True, default=dict, help_text='Track what was cleaned up: {s3_files: bool, dns_records: bool, etc.}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deprovisioning', to='workspace_core.workspace')),
            ],
            options={
                'db_table': 'workspace_deprovisioning_records',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(help_text='Primary customer identifier (MTN/Orange Mobile Money)', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in E.164 format', regex='^\\+?[1-9]\\d{1,14}$')])),
                ('name', models.CharField(help_text='Customer full name', max_length=255)),
                ('email', models.EmailField(blank=True, help_text='Customer email (optional)', max_length=254)),
                ('customer_type', models.CharField(choices=[('student', 'Student'), ('business', 'Small Business'), ('individual', 'Individual'), ('corporate', 'Corporate')], default='individual', help_text='Customer type for segmentation', max_length=20)),
                ('city', models.CharField(blank=True, help_text='Customer city', max_length=100)),
                ('region', models.CharField(blank=True, choices=[('littoral', 'Littoral'), ('centre', 'Centre'), ('sud', 'South'), ('nord', 'North'), ('extreme-nord', 'Extreme North'), ('est', 'East'), ('ouest', 'West'), ('nord-ouest', 'North West'), ('sud-ouest', 'South West'), ('adamawa', 'Adamawa')], help_text='Cameroon region', max_length=50)),
                ('address', models.TextField(blank=True, help_text='Customer street/physical address')),
                ('total_orders', models.PositiveIntegerField(default=0, help_text='Total orders across all workspaces')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, help_text='Total amount spent across all workspaces', max_digits=12)),
                ('first_order_at', models.DateTimeField(blank=True, help_text='First order date', null=True)),
                ('last_order_at', models.DateTimeField(blank=True, help_text='Last order date', null=True)),
                ('tags', models.JSONField(default=list, help_text="Customer tags for segmentation ['vip', 'wholesale', 'frequent', 'student']")),
                ('sms_notifications', models.BooleanField(default=True, help_text='Opt-in for SMS notifications')),
                ('whatsapp_notifications', models.BooleanField(default=True, help_text='Opt-in for WhatsApp notifications')),
                ('is_active', models.BooleanField(default=True, help_text='Whether customer is active')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When customer was verified', null=True)),
                ('workspace', models.ForeignKey(help_text='Workspace this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='workspace_core.workspace')),
            ],
            options={
                'db_table': 'workspace_customers',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('invite', 'Invite User'), ('remove', 'Remove User'), ('role_change', 'Role Change'), ('settings_change', 'Settings Change'), ('billing_change', 'Billing Change')], help_text='Type of action performed', max_length=50)),
                ('resource_type', models.CharField(blank=True, help_text='Type of resource affected', max_length=100)),
                ('resource_id', models.CharField(blank=True, help_text='ID of affected resource', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Human-readable description of the action')),
                ('metadata', models.JSONField(default=dict, help_text='Additional action metadata')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='workspace_core.workspace')),
            ],
            options={
                'db_table': 'workspace_audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceNotificationSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sms_enabled', models.BooleanField(default=False, help_text='Enable SMS notifications')),
                ('sms_provider', models.CharField(blank=True, choices=[('mtn', 'MTN Cameroon'), ('orange', 'Orange Cameroon'), ('camtel', 'Camtel')], help_text='SMS provider for Cameroon market', max_length=20)),
                ('sms_sender_name', models.CharField(blank=True, help_text='Sender name for SMS (max 11 chars)', max_length=11)),
                ('sms_api_key', models.CharField(blank=True, help_text='API key for SMS provider (encrypted)', max_length=255)),
                ('whatsapp_enabled', models.BooleanField(default=False, help_text='Enable WhatsApp notifications')),
                ('whatsapp_business_number', models.CharField(blank=True, help_text='WhatsApp Business phone number with country code', max_length=20)),
                ('whatsapp_api_token', models.CharField(blank=True, help_text='WhatsApp Business API token (encrypted)', max_length=255)),
                ('email_enabled', models.BooleanField(default=False, help_text='Enable email notifications (rarely used in Cameroon)')),
                ('email_sender_name', models.CharField(blank=True, help_text='Name shown in email sender field', max_length=100)),
                ('email_sender_address', models.EmailField(blank=True, help_text='Email address for sending notifications', max_length=254)),
                ('notification_events', models.JSONField(blank=True, default=dict, help_text='Per-event notification channel preferences')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='workspace_core.workspace')),
            ],
            options={
                'db_table': 'workspace_notification_settings',
            },
        ),
        migrations.CreateModel(
            name='CustomerAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(help_text="Hashed password using Django's make_password()", max_length=128)),
                ('email_verified', models.BooleanField(default=False, help_text="Whether customer's email has been verified")),
                ('email_verification_token', models.CharField(blank=True, help_text='Token for email verification', max_length=255)),
                ('email_verification_expires', models.DateTimeField(blank=True, help_text='When email verification token expires', null=True)),
                ('password_reset_token', models.CharField(blank=True, help_text='Token for password reset', max_length=255)),
                ('password_reset_expires', models.DateTimeField(blank=True, help_text='When password reset token expires', null=True)),
                ('last_login', models.DateTimeField(blank=True, help_text='Last successful login timestamp', null=True)),
                ('login_attempts', models.PositiveIntegerField(default=0, help_text='Failed login attempts (for security)')),
                ('locked_until', models.DateTimeField(blank=True, help_text='Account locked until this time (after multiple failed attempts)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(help_text='Customer this authentication belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='auth', to='workspace_core.customer')),
            ],
            options={
                'db_table': 'customer_auth',
                'indexes': [models.Index(fields=['customer'], name='customer_au_custome_8936af_idx'), models.Index(fields=['email_verification_token'], name='customer_au_email_v_74a61b_idx'), models.Index(fields=['password_reset_token'], name='customer_au_passwor_e6bcfc_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeProvisioningLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('retrying', 'Retrying')], max_length=20)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('attempt', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('deprovisioning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='workspace_core.deprovisioningrecord')),
            ],
            options={
                'db_table': 'workspace_deprovisioning_logs',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['deprovisioning', 'timestamp'], name='workspace_d_deprovi_853e2b_idx'), models.Index(fields=['step', 'status'], name='workspace_d_step_862b49_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProvisioningLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed'), ('retrying', 'Retrying')], max_length=20)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('attempt', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('provisioning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='workspace_core.provisioningrecord')),
            ],
            options={
                'db_table': 'workspace_provisioning_logs',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['provisioning', 'timestamp'], name='workspace_p_provisi_4ea3a9_idx'), models.Index(fields=['step', 'status'], name='workspace_p_step_a74436_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['owner', 'status'], name='workspaces_owner_i_448a2c_idx'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['type', 'status'], name='workspaces_type_fae325_idx'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['slug'], name='workspaces_slug_cac896_idx'),
        ),
        migrations.AddIndex(
            model_name='provisioningrecord',
            index=models.Index(fields=['workspace', 'status'], name='workspace_p_workspa_dd475d_idx'),
        ),
        migrations.AddIndex(
            model_name='provisioningrecord',
            index=models.Index(fields=['status', 'created_at'], name='workspace_p_status_2c112c_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['user', 'is_active'], name='workspace_m_user_id_e10463_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['workspace', 'is_active'], name='workspace_m_workspa_2a7a3e_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['role'], name='workspace_m_role_id_046c12_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('user', 'workspace')},
        ),
        migrations.AddIndex(
            model_name='deprovisioningrecord',
            index=models.Index(fields=['workspace', 'status'], name='workspace_d_workspa_fae447_idx'),
        ),
        migrations.AddIndex(
            model_name='deprovisioningrecord',
            index=models.Index(fields=['status', 'scheduled_for'], name='workspace_d_status_054a03_idx'),
        ),
        migrations.AddIndex(
            model_name='deprovisioningrecord',
            index=models.Index(fields=['scheduled_for'], name='workspace_d_schedul_911425_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['workspace', 'phone'], name='workspace_c_workspa_f5a520_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['workspace', 'customer_type'], name='workspace_c_workspa_dae341_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['workspace', 'region'], name='workspace_c_workspa_b96118_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['workspace', 'is_active'], name='workspace_c_workspa_1fcd8c_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone'], name='workspace_c_phone_69873c_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['total_spent'], name='workspace_c_total_s_334959_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['workspace', '-timestamp'], name='workspace_a_workspa_24e7a4_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-timestamp'], name='workspace_a_user_id_14089a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-timestamp'], name='workspace_a_action_51aaa8_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['resource_type', '-timestamp'], name='workspace_a_resourc_5f790b_idx'),
        ),
    ]
