# Generated by Django 6.0 on 2025-12-28 10:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('key', models.CharField(help_text="Permission key in format 'resource:action' (e.g., 'product:create')", max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField(help_text='Human-readable description of what this permission allows')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'workspace_permissions',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission_key', models.CharField(help_text='Permission key from Permission model', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'workspace_role_permissions',
                'ordering': ['permission_key'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Email address of person being invited', max_length=254)),
                ('token', models.CharField(db_index=True, help_text='Secure token for accepting invitation', max_length=64, unique=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('SENT', 'Sent'), ('ACCEPTED', 'Accepted'), ('CONSUMED', 'Consumed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], db_index=True, default='CREATED', max_length=20)),
                ('expires_at', models.DateTimeField(db_index=True, help_text='When this invitation expires')),
                ('accepted_at', models.DateTimeField(blank=True, help_text='When invitation was accepted', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'workspace_invites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='membership',
            name='workspace_m_user_id_e10463_idx',
        ),
        migrations.RemoveIndex(
            model_name='membership',
            name='workspace_m_workspa_2a7a3e_idx',
        ),
        # Add fields FIRST before using them in constraints
        migrations.AddField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('INVITED', 'Invited'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], db_index=True, default='ACTIVE', help_text='Membership status in invitation lifecycle', max_length=20),
        ),
        migrations.AddField(
            model_name='role',
            name='is_system',
            field=models.BooleanField(db_index=True, default=False, help_text='System roles are auto-provisioned and cannot be deleted'),
        ),
        migrations.AddField(
            model_name='role',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text='Workspace this role belongs to. NULL for system/default roles.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='workspace_core.workspace'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(help_text="Role name (e.g., 'Owner', 'Admin', 'Staff', 'ReadOnly')", max_length=100),
        ),
        # NOW we can use workspace in constraints
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['workspace', 'name']},
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('workspace', 'name')},
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['user', 'status'], name='workspace_m_user_id_de9200_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['workspace', 'status'], name='workspace_m_workspa_ce57d5_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['workspace', 'user', 'status'], name='workspace_m_workspa_3cd3ac_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['workspace', 'name'], name='workspace_r_workspa_0e3679_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['is_system'], name='workspace_r_is_syst_3fca73_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['workspace', 'is_system'], name='workspace_r_workspa_f432a9_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['key'], name='workspace_p_key_6360f6_idx'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='workspace_core.role'),
        ),
        migrations.AddField(
            model_name='workspaceinvite',
            name='accepted_by',
            field=models.ForeignKey(blank=True, help_text='User who accepted (may differ from invited email for existing users)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workspaceinvite',
            name='invited_by',
            field=models.ForeignKey(help_text='User who sent the invitation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workspaceinvite',
            name='role',
            field=models.ForeignKey(help_text='Role to assign when invite is accepted', on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='workspace_core.role'),
        ),
        migrations.AddField(
            model_name='workspaceinvite',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='workspace_core.workspace'),
        ),
        migrations.RemoveField(
            model_name='membership',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['role', 'permission_key'], name='workspace_r_role_id_512fce_idx'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['permission_key'], name='workspace_r_permiss_e221eb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission_key')},
        ),
        migrations.AddIndex(
            model_name='workspaceinvite',
            index=models.Index(fields=['workspace', 'email', 'status'], name='workspace_i_workspa_233b5e_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceinvite',
            index=models.Index(fields=['token'], name='workspace_i_token_1a6fb9_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceinvite',
            index=models.Index(fields=['status', 'expires_at'], name='workspace_i_status_ce83d3_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceinvite',
            index=models.Index(fields=['workspace', 'status'], name='workspace_i_workspa_be2c33_idx'),
        ),
    ]
