# Generated by Django 6.0 on 2025-12-28 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace_core', '0002_permission_rolepermission_workspaceinvite_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='invited_by',
            field=models.ForeignKey(blank=True, help_text='User who invited this member', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membership',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='removed_by',
            field=models.ForeignKey(blank=True, help_text='User who removed this membership', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removed_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membership',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='suspended_by',
            field=models.ForeignKey(blank=True, help_text='User who suspended this membership', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspended_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membership',
            name='suspension_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('INVITED', 'Invited'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('REMOVED', 'Removed')], db_index=True, default='ACTIVE', help_text='Membership status in invitation lifecycle', max_length=20),
        ),
    ]
