# Generated by Django 6.0 on 2025-12-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace_core', '0003_add_membership_suspension_removal_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Description of role responsibilities and permissions'),
        ),
    ]
