# Generated by Django 6.0 on 2025-12-28 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace_core', '0004_add_role_description'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='membership',
            name='workspace_m_role_id_046c12_idx',
        ),
        migrations.RemoveField(
            model_name='workspaceinvite',
            name='role',
        ),
        migrations.AddField(
            model_name='membership',
            name='roles',
            field=models.ManyToManyField(help_text='Roles assigned to this membership (supports multiple roles per user)', related_name='memberships', to='workspace_core.role'),
        ),
        migrations.AddField(
            model_name='workspaceinvite',
            name='roles',
            field=models.ManyToManyField(help_text='Roles to assign when invite is accepted (supports multiple)', related_name='invites', to='workspace_core.role'),
        ),
        migrations.RemoveField(
            model_name='membership',
            name='role',
        ),
    ]
