# Generated by Django 6.0 on 2025-12-28 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace_core', '0005_remove_membership_workspace_m_role_id_046c12_idx_and_more'),
    ]

    operations = [
    ]
