# Generated by Django 6.0 on 2026-01-03 05:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace_core', '0006_migrate_roles_to_m2m'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(db_index=True, help_text="Type of action (e.g., 'order_placed', 'note_added')", max_length=50)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Structured event details')),
                ('customer', models.ForeignKey(help_text='Customer this history entry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='workspace_core.customer')),
                ('performed_by', models.ForeignKey(blank=True, help_text='User who performed the action (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_history_actions', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(help_text='Workspace this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='workspace_core.workspace')),
            ],
            options={
                'db_table': 'workspace_customer_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'customer', '-created_at'], name='workspace_c_workspa_3a8aea_idx'), models.Index(fields=['action'], name='workspace_c_action_aa0440_idx')],
            },
        ),
    ]
