# Generated by Django 6.0 on 2026-01-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace_core', '0007_customerhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text="Customer tags for segmentation ['vip', 'wholesale', 'frequent', 'student']"),
        ),
    ]
