# Generated by Django 6.0 on 2026-01-05 13:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace_core', '0008_alter_customer_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='compliance_deadline',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When auto-enforcement triggers (7 days after violation detected)', null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='enforcement_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Details of what was enforced: suspended workspaces, deactivated products, etc.'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='plan_status',
            field=models.CharField(choices=[('compliant', 'Compliant'), ('plan_violation', 'Plan Violation'), ('auto_enforced', 'Auto Enforced')], db_index=True, default='compliant', help_text='Compliance status: compliant, plan_violation, or auto_enforced', max_length=20),
        ),
        migrations.AddField(
            model_name='workspace',
            name='violation_types',
            field=models.JSONField(blank=True, default=list, help_text='List of violated caps: workspaces, products, staff, domains, themes, payment'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='status',
            field=models.CharField(choices=[('provisioning', 'Provisioning'), ('active', 'Active'), ('suspended', 'Suspended'), ('suspended_by_plan', 'Suspended by Plan'), ('pending', 'Pending Approval')], default='provisioning', max_length=20),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['plan_status', 'compliance_deadline'], name='workspaces_plan_st_4734b8_idx'),
        ),
    ]
