# Generated by Django 6.0 on 2026-01-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace_core', '0009_workspace_compliance_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='restricted_at',
            field=models.DateTimeField(blank=True, help_text='When restricted_mode was enabled (for tracking reactivation eligibility)', null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='restricted_mode',
            field=models.BooleanField(db_index=True, default=False, help_text='True when owner subscription is restricted - blocks all new actions until reactivation'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='restricted_reason',
            field=models.CharField(blank=True, default='', help_text='Reason for restriction: grace_period_expired, payment_failed, admin_action', max_length=50),
        ),
    ]
