# Generated by Django 6.0 on 2025-12-09 09:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_event_id', models.CharField(db_index=True, help_text='Unique event ID from provider', max_length=200, unique=True)),
                ('provider_name', models.CharField(max_length=50)),
                ('payload', models.JSONField(help_text='Raw webhook payload')),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Event Log',
                'verbose_name_plural': 'Event Logs',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['provider_event_id'], name='payments_ev_provide_c06afc_idx'), models.Index(fields=['processed', 'received_at'], name='payments_ev_process_2e5caa_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(db_index=True, help_text='Workspace/Store ID', max_length=100)),
                ('amount', models.IntegerField(help_text='Amount in smallest currency unit')),
                ('currency', models.CharField(choices=[('XAF', 'Central African CFA Franc'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='XAF', max_length=3)),
                ('purpose', models.CharField(choices=[('subscription', 'Subscription Payment'), ('subscription_renewal', 'Subscription Renewal'), ('subscription_upgrade', 'Subscription Upgrade'), ('domain', 'Domain Purchase'), ('theme', 'Theme Purchase'), ('checkout', 'Store Checkout'), ('trial', 'Trial Subscription'), ('other', 'Other')], db_index=True, max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context data')),
                ('provider_name', models.CharField(blank=True, db_index=True, help_text='Payment provider (fapshi, mtn, orange, etc.)', max_length=50, null=True)),
                ('provider_intent_id', models.CharField(blank=True, help_text="Provider's transaction ID", max_length=200, null=True, unique=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='created', max_length=20)),
                ('idempotency_key', models.CharField(db_index=True, help_text='Unique key to prevent duplicate payments', max_length=100, unique=True)),
                ('created_by_user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(help_text='Payment session expires after 30 minutes (OWASP/PCI DSS)')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_intents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Intent',
                'verbose_name_plural': 'Payment Intents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(help_text='Refund amount in smallest currency unit')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='requested', max_length=20)),
                ('provider_refund_id', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('payment_intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.paymentintent')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Refund Request',
                'verbose_name_plural': 'Refund Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('payment_created', 'Payment Created'), ('payment_confirmed', 'Payment Confirmed'), ('payment_failed', 'Payment Failed'), ('webhook_received', 'Webhook Received'), ('refund_initiated', 'Refund Initiated'), ('refund_completed', 'Refund Completed'), ('reconciliation', 'Reconciliation Check')], db_index=True, max_length=30)),
                ('provider_name', models.CharField(max_length=50)),
                ('provider_response', models.JSONField(help_text='Raw provider API response or webhook payload')),
                ('status', models.CharField(help_text='Status from provider', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('request_metadata', models.JSONField(blank=True, default=dict, help_text='Request details (headers, IP, user agent)')),
                ('payment_intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_logs', to='payments.paymentintent')),
            ],
            options={
                'verbose_name': 'Transaction Log',
                'verbose_name_plural': 'Transaction Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MerchantPaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(db_index=True, max_length=100)),
                ('provider_name', models.CharField(db_index=True, help_text='Payment provider (fapshi, mtn, orange, flutterwave)', max_length=50)),
                ('config_encrypted', models.TextField(help_text='Encrypted provider credentials and config (KMS encrypted)')),
                ('enabled', models.BooleanField(default=False, help_text='Merchant has enabled this payment method')),
                ('verified', models.BooleanField(default=False, help_text='Credentials verified with test call')),
                ('permissions', models.JSONField(blank=True, default=dict, help_text='What this provider supports (card, mobile-money, redirect, etc.)')),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('total_transactions', models.IntegerField(default=0)),
                ('successful_transactions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('workspace_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Merchant Payment Method',
                'verbose_name_plural': 'Merchant Payment Methods',
                'ordering': ['-enabled', '-last_used_at'],
                'indexes': [models.Index(fields=['workspace_id', 'enabled'], name='payments_me_workspa_e34909_idx'), models.Index(fields=['provider_name', 'enabled'], name='payments_me_provide_e9d6b0_idx')],
                'unique_together': {('workspace_id', 'provider_name')},
            },
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['workspace_id', 'status'], name='payments_pa_workspa_181d70_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['user', 'status'], name='payments_pa_user_id_503f5b_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['provider_intent_id'], name='payments_pa_provide_5cc0ea_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['idempotency_key'], name='payments_pa_idempot_fb5e02_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['created_at'], name='payments_pa_created_8a067b_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['status', 'created_at'], name='payments_pa_status_79eeea_idx'),
        ),
        migrations.AddIndex(
            model_name='refundrequest',
            index=models.Index(fields=['payment_intent', 'status'], name='payments_re_payment_1f0bf0_idx'),
        ),
        migrations.AddIndex(
            model_name='refundrequest',
            index=models.Index(fields=['status', 'created_at'], name='payments_re_status_9d8b07_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['payment_intent', 'created_at'], name='payments_tr_payment_c1b501_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['event_type', 'created_at'], name='payments_tr_event_t_f0fa88_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['created_at'], name='payments_tr_created_714f6a_idx'),
        ),
    ]
