# Generated by Django 6.0 on 2025-12-17 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentintent',
            name='original_payment_intent_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Original PaymentIntent ID if this is a retry (for analytics and debugging)', null=True),
        ),
    ]
