# Generated by Django 6.0 on 2026-01-02 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentintent_original_payment_intent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantpaymentmethod',
            name='checkout_url',
            field=models.URLField(blank=True, help_text="Merchant's payment checkout URL (for external redirect providers)", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='merchantpaymentmethod',
            name='config_encrypted',
            field=models.TextField(blank=True, default='', help_text='Encrypted provider credentials (for future API-integrated providers)'),
        ),
        migrations.AlterField(
            model_name='merchantpaymentmethod',
            name='verified',
            field=models.BooleanField(default=False, help_text='URL validated or credentials verified'),
        ),
    ]
