# Generated by Django 6.0 on 2026-01-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_merchantpaymentmethod_checkout_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentintent',
            name='workspace_id',
            field=models.CharField(blank=True, db_index=True, help_text='Workspace/Store ID (optional for user-level payments)', max_length=100, null=True),
        ),
    ]
